package cookie

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"sync"

	"github.com/kumneger0/ytmusic-tui/internal/config"
)

var (
	cachedCookieHeader string
	cookieHeaderOnce   sync.Once
)

func ResetCookieHeaderCache() {
	cachedCookieHeader = ""
	cookieHeaderOnce = sync.Once{}
}

func ConvertToNetscapeCookies(cookieText string) string {
	cookieText = strings.TrimSpace(cookieText)
	if cookieText == "" {
		return "# Netscape HTTP Cookie File\n"
	}

	if strings.HasPrefix(cookieText, "# Netscape HTTP Cookie File") || strings.HasPrefix(cookieText, "# HTTP Cookie File") {
		return cookieText
	}

	lines := []string{}
	for _, l := range strings.Split(cookieText, "\n") {
		trimmed := strings.TrimSpace(l)
		if trimmed != "" && !strings.HasPrefix(trimmed, "#") {
			lines = append(lines, trimmed)
		}
	}

	if len(lines) > 0 {
		allTab7 := true
		for _, l := range lines {
			if len(strings.Split(l, "\t")) < 7 {
				allTab7 = false
				break
			}
		}
		if allTab7 {
			return fmt.Sprintf("# Netscape HTTP Cookie File\n\n%s", cookieText)
		}
	}

	cookieHeaderStr := cookieText
	var rawData interface{}
	if err := json.Unmarshal([]byte(cookieText), &rawData); err == nil {
		switch v := rawData.(type) {
		case map[string]interface{}:
			if c, ok := v["Cookie"].(string); ok && c != "" {
				cookieHeaderStr = c
			} else if c, ok := v["cookie"].(string); ok && c != "" {
				cookieHeaderStr = c
			} else if headersObj, ok := v["headers"].(map[string]interface{}); ok {
				if c, ok := headersObj["Cookie"].(string); ok && c != "" {
					cookieHeaderStr = c
				} else if c, ok := headersObj["cookie"].(string); ok && c != "" {
					cookieHeaderStr = c
				}
			}
		case []interface{}:
			netscapeLines := []string{
				"# Netscape HTTP Cookie File",
				"# https://curl.se/docs/http-cookies.html",
				"# This file was generated by clispot",
				"",
			}
			for _, item := range v {
				if itemMap, ok := item.(map[string]interface{}); ok {
					name := ""
					if n, ok := itemMap["name"]; ok && n != nil {
						name = fmt.Sprintf("%v", n)
					}
					val := ""
					if vVal, ok := itemMap["value"]; ok && vVal != nil {
						val = fmt.Sprintf("%v", vVal)
					}
					if name != "" && val != "" {
						domain := ".youtube.com"
						if d, ok := itemMap["domain"]; ok && d != nil {
							domain = fmt.Sprintf("%v", d)
						}
						httpOnly := false
						if ho, ok := itemMap["httpOnly"].(bool); ok {
							httpOnly = ho
						}
						if httpOnly && !strings.HasPrefix(domain, "#HttpOnly_") {
							domain = "#HttpOnly_" + domain
						}
						flag := "FALSE"
						if strings.HasPrefix(domain, ".") || strings.HasPrefix(domain, "#HttpOnly_.") {
							flag = "TRUE"
						}
						path := "/"
						if p, ok := itemMap["path"]; ok && p != nil {
							path = fmt.Sprintf("%v", p)
						}
						secure := "TRUE"
						if sec, ok := itemMap["secure"].(bool); ok && !sec {
							secure = "FALSE"
						}
						var expiry int64 = 2147483647
						if expVal, ok := itemMap["expirationDate"]; ok && expVal != nil {
							if expInt, err := strconv.ParseInt(fmt.Sprintf("%.0f", expVal), 10, 64); err == nil {
								expiry = expInt
							}
						} else if expVal, ok := itemMap["expiry"]; ok && expVal != nil {
							if expInt, err := strconv.ParseInt(fmt.Sprintf("%.0f", expVal), 10, 64); err == nil {
								expiry = expInt
							}
						} else if expVal, ok := itemMap["expires"]; ok && expVal != nil {
							if expInt, err := strconv.ParseInt(fmt.Sprintf("%.0f", expVal), 10, 64); err == nil {
								expiry = expInt
							}
						}
						netscapeLines = append(netscapeLines, fmt.Sprintf("%s\t%s\t%s\t%s\t%d\t%s\t%s", domain, flag, path, secure, expiry, name, val))
					}
				}
			}
			return strings.Join(netscapeLines, "\n")
		}
	}

	netscapeLines := []string{
		"# Netscape HTTP Cookie File",
		"# https://curl.se/docs/http-cookies.html",
		"# This file was generated by clispot",
		"",
	}
	reHeader := regexp.MustCompile(`(?i)^(cookie|Cookie):\s*`)
	rawStr := reHeader.ReplaceAllString(strings.TrimSpace(cookieHeaderStr), "")
	reSplit := regexp.MustCompile(`[;\r\n]+`)
	items := reSplit.Split(rawStr, -1)
	for _, itemStr := range items {
		cleanItem := strings.TrimSpace(itemStr)
		if cleanItem == "" || !strings.Contains(cleanItem, "=") {
			continue
		}
		parts := strings.SplitN(cleanItem, "=", 2)
		cookieName := strings.TrimSpace(parts[0])
		cookieVal := strings.TrimSpace(parts[1])
		if cookieName == "" {
			continue
		}
		netscapeLines = append(netscapeLines, fmt.Sprintf(".youtube.com\tTRUE\t/\tTRUE\t2147483647\t%s\t%s", cookieName, cookieVal))
	}

	return strings.Join(netscapeLines, "\n")
}

func GetCookieFilePath() string {
	configDir := config.GetConfigDir(runtime.GOOS)
	return filepath.Join(configDir, "cookie.txt")
}

func SaveCookieFile(cookieText string) (string, error) {
	ResetCookieHeaderCache()
	cookiePath := GetCookieFilePath()
	netscapeContent := ConvertToNetscapeCookies(cookieText)

	if err := os.WriteFile(cookiePath, []byte(netscapeContent), 0600); err != nil {
		slog.Error("failed to write cookie.txt", "err", err)
		return "", err
	}

	if err := os.Chmod(cookiePath, 0600); err != nil {
		slog.Error("failed to set permissions on cookie.txt", "err", err)
	}

	return cookiePath, nil
}

func EnsureCookieFile() string {
	cookiePath := GetCookieFilePath()
	configDir := config.GetConfigDir(runtime.GOOS)
	browserPath := filepath.Join(configDir, "browser.json")

	browserData, err := os.ReadFile(browserPath)
	if err != nil || len(browserData) == 0 {
		if fi, err := os.Stat(cookiePath); err == nil && fi.Size() > 0 {
			return cookiePath
		}
		return ""
	}

	path, err := SaveCookieFile(string(browserData))
	if err != nil {
		return ""
	}
	return path
}

func GetCookieHeader() string {
	cookieHeaderOnce.Do(func() {
		configDir := config.GetConfigDir(runtime.GOOS)
		browserPath := filepath.Join(configDir, "browser.json")
		if browserData, err := os.ReadFile(browserPath); err == nil && len(browserData) > 0 {
			var rawData map[string]interface{}
			if err := json.Unmarshal(browserData, &rawData); err == nil {
				if c, ok := rawData["Cookie"].(string); ok && c != "" {
					cachedCookieHeader = c
					return
				}
				if c, ok := rawData["cookie"].(string); ok && c != "" {
					cachedCookieHeader = c
					return
				}
				if headersObj, ok := rawData["headers"].(map[string]interface{}); ok {
					if c, ok := headersObj["Cookie"].(string); ok && c != "" {
						cachedCookieHeader = c
						return
					}
					if c, ok := headersObj["cookie"].(string); ok && c != "" {
						cachedCookieHeader = c
						return
					}
				}
			}
		}
	})
	return cachedCookieHeader
}
