name: golangci-lint
on:
  push:
    paths:
      - '**.go'
    branches:
      - main
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: '1.26.x'

      - name: Set up uv and Python 3.13
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
           python-version: '3.13'
           enable-cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libasound2-dev gcc-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Sync Python dependencies
        run: uv sync

      - name: Install buf Proto Compiler s
        run: npm install -g @bufbuild/buf

      - name: Generate Go Protobuf files
        run: | 
          make proto
          make build

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: -c .golangci.yml -v --timeout=10m