name: test
on:
  push:
    paths:
      - '**.go'
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: '1.26.x'

      - name: Set up uv and Python 3.13
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
           python-version: '3.13'
           enable-cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libasound2-dev protobuf-compiler gcc-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Sync Python dependencies
        run: uv sync

      - name: Install buf Proto Compiler
        run: npm install -g @bufbuild/buf

      - name: Generate Go Protobuf files
        run: | 
          buf generate --template buf.gen.go.yaml
          make build

      - name: test
        run: go test ./...